dist: trusty

language: python

addons:
  mariadb: 10.3

jobs:
  include:
  - name: "Python 2.7 Server Side Test"
    python: 2.7
    script: bench run-tests --app erpnext --coverage

  - name: "Python 3.6 Server Side Test"
    python: 3.6
    script: bench run-tests --app erpnext --coverage

  - name: "Python 2.7 Patch Test"
    python: 2.7
    before_script:
      - wget http://build.erpnext.com/20171108_190013_955977f8_database.sql.gz
      - bench --force restore ~/frappe-bench/20171108_190013_955977f8_database.sql.gz --mariadb-root-password travis
    script: bench migrate

  - name: "Python 3.6 Patch Test"
    python: 3.6
    before_script:
      - wget http://build.erpnext.com/20171108_190013_955977f8_database.sql.gz
      - bench --force restore ~/frappe-bench/20171108_190013_955977f8_database.sql.gz --mariadb-root-password travis
    script: bench migrate

install:
  # fix mongodb travis error
  - nvm install 10
  - pip install python-coveralls
  - wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
  - sudo python install.py --develop --user travis --without-bench-setup
  - sudo pip install -e ~/bench

  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - bash $TRAVIS_BUILD_DIR/travis/bench_init.sh
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/

before_script:
  - mysql -u root -ptravis -e 'create database test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis

  - cd ~/frappe-bench
  - bench get-app erpnext $TRAVIS_BUILD_DIR
  - bench use test_site
  - bench reinstall --mariadb-root-username root --mariadb-root-password travis --yes
  - bench scheduler disable
  - sed -i 's/9000/9001/g' sites/common_site_config.json
  - bench start &
  - sleep 10

after_script:
  - coveralls -b apps/erpnext -d ../../sites/.coverage
