language: python

python:
  - "2.7"

services:
  - mysql

install:
  - sudo service mysql stop
  - sudo apt-get install python-software-properties
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'
  - sudo apt-get update
  - sudo apt-get purge -y mysql-common
  - sudo apt-get install mariadb-server mariadb-common libmariadbclient-dev
  - ./ci/fix-mariadb.sh

  - wget http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb
  - CFLAGS=-O0 pip install git+https://github.com/frappe/frappe.git@v5.0
  - CFLAGS=-O0 pip install --editable .

before_script:
  - mysql -e 'create database test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root

script:
  - cd ./test_sites/
  - frappe --use test_site
  - frappe --reinstall
  - frappe --install_app erpnext --verbose
  - frappe -b
  - frappe --build_website
  - frappe --serve_test &
  - frappe --verbose --run_tests --app erpnext
