[["Currency Exchange"]]
date = "2016-01-01"
exchange_rate = 60.0
from_currency = "USD"
to_currency = "INR"
for_buying = 1
for_selling = 0

[["Currency Exchange"]]
date = "2016-01-01"
exchange_rate = 0.773
from_currency = "USD"
to_currency = "EUR"
for_buying = 0
for_selling = 1

[["Currency Exchange"]]
date = "2016-01-01"
exchange_rate = 0.0167
from_currency = "INR"
to_currency = "USD"
for_buying = 1
for_selling = 0

[["Currency Exchange"]]
date = "2016-01-10"
exchange_rate = 65.1
from_currency = "USD"
to_currency = "INR"
for_buying = 1
for_selling = 0

[["Currency Exchange"]]
date = "2016-01-30"
exchange_rate = 62.9
from_currency = "USD"
to_currency = "INR"
for_buying = 1
for_selling = 1

[["Currency Exchange"]]
date = "2016-01-10"
exchange_rate = 65.1
from_currency = "INR"
to_currency = "NGN"
for_buying = 1
for_selling = 1

