[[Opportunity]]
name = "_Test Opportunity 1"
opportunity_from = "Lead"
enquiry_type = "Sales"
party_name = "_T-Lead-00001"
transaction_date = "2013-12-12"
[[Opportunity.items]]
item_name = "Test Item"
description = "Some description"
qty = 5
rate = 100


