[["Item Price"]]
item_code = "_Test Item"
price_list = "_Test Price List"
price_list_rate = 100
valid_from = "2017-04-18"
valid_upto = "2017-04-26"

[["Item Price"]]
item_code = "_Test Item"
price_list = "_Test Price List Rest of the World"
price_list_rate = 10

[["Item Price"]]
item_code = "_Test Item 2"
price_list = "_Test Price List Rest of the World"
price_list_rate = 20
valid_from = "2017-04-18"
valid_upto = "2017-04-26"
customer = "_Test Customer"
uom = "_Test UOM"

[["Item Price"]]
item_code = "_Test Item Home Desktop 100"
price_list = "_Test Price List"
price_list_rate = 1000
valid_from = "2017-04-10"
valid_upto = "2017-04-17"

[["Item Price"]]
item_code = "_Test Item Home Desktop Manufactured"
price_list = "_Test Price List"
price_list_rate = 1000
valid_from = "2017-04-10"
valid_upto = "2017-04-17"

[["Item Price"]]
item_code = "_Test Item"
price_list = "_Test Buying Price List"
price_list_rate = 100
supplier = "_Test Supplier"

[["Item Price"]]
item_code = "_Test Item"
price_list = "_Test Selling Price List"
price_list_rate = 200
customer = "_Test Customer"

