[[Employee]]
company = "_Test Company"
date_of_birth = "1980-01-01"
date_of_joining = "2010-01-01"
department = "_Test Department - _TC"
first_name = "_Test Employee"
gender = "Female"
naming_series = "_T-Employee-"
status = "Active"
user_id = "test@example.com"

[[Employee]]
company = "_Test Company"
date_of_birth = "1980-01-01"
date_of_joining = "2010-01-01"
department = "_Test Department 1 - _TC"
first_name = "_Test Employee 1"
gender = "Male"
naming_series = "_T-Employee-"
status = "Active"
user_id = "test1@example.com"

[[Employee]]
company = "_Test Company"
date_of_birth = "1980-01-01"
date_of_joining = "2010-01-01"
department = "_Test Department 1 - _TC"
first_name = "_Test Employee 2"
gender = "Male"
naming_series = "_T-Employee-"
status = "Active"
user_id = "test2@example.com"

